# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Walkr
email: your-email@domain.com
members: Steve, Minghe, Tian, Dan
description: > # this means to ignore newlines until "baseurl:"
  Here is the awesome description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/com381-525/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
